apiVersion: v1
kind: Pod
metadata:
  name: github-runner-gpu
  labels:
    app: github-runner-gpu
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 6Gi
  containers:
    - name: github-runner-gpu
      image: ghcr.io/cristhianarv/mlops-project/github-runner:latest
      # We mount a shared memory volume for training
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      env:
        - name: GITHUB_RUNNER_LABEL
          value: "gpu-runner"
        - name: GITHUB_RUNNER_PAT
          valueFrom:
            secretKeyRef:
              name: github-runner-pat
              key: token
      securityContext:
        runAsUser: 1000
      resources:
        limits:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: "6Gi"
          nvidia.com/gpu: "1"
  nodeSelector:
    gpu: "true"